package:
  name:    listfile
  version: 1.0

source:
  git_rev: 1.0
  git_url: https://github.com/UCL-EO/listfile

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python>=3.6
    - setuptools

  run:
    - python

test:
  imports:
    -

about:
  home: https://github.com/UCL-EO/listfile
